FROM python:3.9
RUN --mount=type=cache,target=/var/lib/apt/lists \
    apt-get update
RUN --mount=type=cache,target=/var/lib/apt/lists \
    apt-get install ffmpeg -y
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install git+https://github.com/openai/whisper.git

