FROM python:3.9-slim
ARG PYTORCH_PACKAGES=cpu
RUN --mount=type=cache,target=/var/lib/apt/lists \
    apt-get update
RUN --mount=type=cache,target=/var/lib/apt/lists \
    apt-get install ffmpeg -y
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install torch --extra-index-url https://download.pytorch.org/whl/$PYTORCH_PACKAGES
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install https://github.com/openai/whisper/archive/refs/heads/main.zip
