FROM python:3.9-slim
ARG PYTORCH_PACKAGES=cpu
RUN apt-get update && apt-get install git -y && rm -rf /var/lib/apt/lists/*
RUN pip install torch --extra-index-url https://download.pytorch.org/whl/$PYTORCH_PACKAGES
RUN pip install git+https://github.com/openai/whisper.git
COPY --from=nixery.dev/ffmpeg /nix/ /nix/
COPY --from=nixery.dev/ffmpeg /bin/ffmpeg /bin/

