FROM alpine AS ffmpeg
WORKDIR /ffmpeg
RUN apk add curl
RUN curl -fsSL https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz \
    | tar x -J --strip-components=1

FROM python:3.9-slim
ARG PYTORCH_PACKAGES=cpu
RUN apt-get update && apt-get install git -y && rm -rf /var/lib/apt/lists/*
RUN pip install torch --extra-index-url https://download.pytorch.org/whl/$PYTORCH_PACKAGES
RUN pip install git+https://github.com/openai/whisper.git
COPY --from=ffmpeg /ffmpeg/ffmpeg /usr/local/bin/ffmpeg

